/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hdyyN98cqZ3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"

export function Component() {
  return (
    (<Carousel className="w-full max-w-4xl">
      <CarouselContent>
        <CarouselItem>
          <div className="relative overflow-hidden rounded-lg">
            <img
              src="/placeholder.svg"
              width={800}
              height={450}
              alt="Carousel Image"
              className="aspect-video w-full object-cover" />
            <div
              className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent p-6 sm:p-8">
              <div className="flex h-full flex-col justify-end gap-2">
                <h3 className="text-2xl font-bold text-white sm:text-3xl">Explore the Outdoors</h3>
                <p className="text-sm text-white/80 sm:text-base">
                  Discover the beauty of nature with our adventure gear.
                </p>
              </div>
            </div>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="relative overflow-hidden rounded-lg">
            <img
              src="/placeholder.svg"
              width={800}
              height={450}
              alt="Carousel Image"
              className="aspect-video w-full object-cover" />
            <div
              className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent p-6 sm:p-8">
              <div className="flex h-full flex-col justify-end gap-2">
                <h3 className="text-2xl font-bold text-white sm:text-3xl">Elevate Your Style</h3>
                <p className="text-sm text-white/80 sm:text-base">
                  Discover the latest fashion trends and accessories.
                </p>
              </div>
            </div>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="relative overflow-hidden rounded-lg">
            <img
              src="/placeholder.svg"
              width={800}
              height={450}
              alt="Carousel Image"
              className="aspect-video w-full object-cover" />
            <div
              className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent p-6 sm:p-8">
              <div className="flex h-full flex-col justify-end gap-2">
                <h3 className="text-2xl font-bold text-white sm:text-3xl">Unleash Your Tech Potential</h3>
                <p className="text-sm text-white/80 sm:text-base">Discover the latest gadgets and tech accessories.</p>
              </div>
            </div>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="relative overflow-hidden rounded-lg">
            <img
              src="/placeholder.svg"
              width={800}
              height={450}
              alt="Carousel Image"
              className="aspect-video w-full object-cover" />
            <div
              className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent p-6 sm:p-8">
              <div className="flex h-full flex-col justify-end gap-2">
                <h3 className="text-2xl font-bold text-white sm:text-3xl">Embrace the Wellness Journey</h3>
                <p className="text-sm text-white/80 sm:text-base">
                  Discover the best wellness products and accessories.
                </p>
              </div>
            </div>
          </div>
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
    </Carousel>)
  );
}
