import Hero from "@/components/Hero/Hero";
import Image from "next/image";
import HomeArticle from "./home-article/page";

export const metadata = {
  title: "Seuj Connect",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Hero />
      <HomeArticle />
    </>
  );
}
